/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class io_github_karlatemp_openagent_OpenAgent */

#ifndef _Included_io_github_karlatemp_openagent_OpenAgent
#define _Included_io_github_karlatemp_openagent_OpenAgent
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     io_github_karlatemp_openagent_OpenAgent
 * Method:    getObjectSize
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_io_github_karlatemp_openagent_OpenAgent_getObjectSize
        (JNIEnv *, jobject);

/*
 * Class:     io_github_karlatemp_openagent_OpenAgent
 * Method:    initialzie
 * Signature: (Ljava/lang/String;)J
 */
JNIEXPORT void JNICALL Java_io_github_karlatemp_openagent_OpenAgent_initialize
        (JNIEnv *, jclass, jstring);

/*
 * Class:     io_github_karlatemp_openagent_OpenAgent
 * Method:    getAllInitializedClasses
 * Signature: ()[Ljava/lang/Class;
 */
JNIEXPORT jobjectArray JNICALL Java_io_github_karlatemp_openagent_OpenAgent_getAllLoadedClasses
        (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
